Add desktop view to the web page
akhror-valiev/micronauts-portfolio pull request #4
Opened 2022-09-29 15:35 UTC by akhror-valiev

- Used flexbox 
 - Used flex grid 
 - Added Desktop view
 - Added Media queries mobile responsive

2022-09-29 16:17 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @akhror-valiev 

Nice job✔, I liked your implementation 🔥, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.
- Good design 🔥🔥🔥 , keep it up.😉

## (Changes Required) Aspects to improve: ♻️
You did great implementing  the project requirements 🔥🔥, but you still have some issues:  
Check the comments below 👇
  
## [Optional] suggestions:

-  Nothing to mention. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-29 16:17 UTC, nedjwab commented on index.html
>      <section class="about-section">
[ ] kindly adjust the work section to be similar to the Figma design 👀, it should take 40% of the container's width, and 4 the text should be 4 to 5 lines.
Your design : 
![histext](https://user-images.githubusercontent.com/62156607/193083178-fb7f5d1b-fc12-4323-add8-532e3534fc4d.PNG)

Figma design : 
![destext](https://user-images.githubusercontent.com/62156607/193083214-65ca9399-8296-4426-a780-b86ec348fbb4.PNG)

2022-09-29 16:17 UTC, nedjwab commented on styles.css
> +  display: grid;
Nice using grid here 🔥🔥🔥🔥

2022-09-29 16:19 UTC, akhror-valiev commented on styles.css
> +  display: grid;
Thanks for your feedback @nedjwab!

2022-09-29 19:43 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @akhror-valiev , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

## Highlights :heavy_check_mark: 
- [ ] Passing linter checks :clap: 
- [ ] Professional readme file :clap: 
- [ ] Descriptive pull request title & summary :clap
- [ ] Correct use of Gitflow :clap: 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Please the inline comment

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 19:43 UTC, Felix45 commented on styles.css
>  }
[Optional] Please consider changing the `background-image`  property's value to `images/contact_form_bg.svg` , currently the background-image for this container is not displaying.  You can also consider making the background image for this section appear the way it is on the Figma template.

```CSS
.contact-container {
  background-image: url(images/contact_form_bg.svg);
  background-repeat: no-repeat;
  background-size: 40vw;
  right: 80px;
  background-color: #6070ff;
  margin: 114px 24px 0 24px;
  margin-top: -10%;
  padding: 114px 24px;
  border-top-left-radius: 100px;
  background-position-x: right;
}
```

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/193124980-339b6c2e-73b4-46f9-91b9-6f5600857614.png" width=400 />

## Your Implementation

<img src="https://user-images.githubusercontent.com/16392046/193125293-f0db08de-3255-4bfa-bc43-9f36fc73e650.png" width=400 />

2022-09-30 03:08 UTC, akhror-valiev commented
Thanks, @Felix45  it is noted and fixed.

2022-09-30 03:10 UTC, merged